# Generated by Django 4.1.5 on 2023-01-18 08:58

import datetime
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('discription', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ttile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=250)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 8, 58, 3, 338350, tzinfo=datetime.timezone.utc))),
                ('portal', models.ForeignKey(on_delete=jobs.models.Portal, to='jobs.portal')),
            ],
        ),
    ]
