# Generated by Django 4.1.5 on 2023-01-18 09:52

import datetime
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=250)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 9, 52, 19, 744347, tzinfo=datetime.timezone.utc))),
                ('portal', models.ForeignKey(on_delete=jobs.models.Portal, to='jobs.portal')),
            ],
        ),
        migrations.DeleteModel(
            name='Ttile',
        ),
    ]
