# Generated by Django 4.1.5 on 2023-01-20 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_title_delete_ttile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 1, 20, 4, 52, 12, 552567, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 4, 52, 12, 552567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=250)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdescription')),
            ],
        ),
    ]
