# Generated by Django 4.1.5 on 2023-01-20 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdescription_alter_title_last_updated_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 5, 8, 31, 88118, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='title',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 5, 8, 31, 88118, tzinfo=datetime.timezone.utc)),
        ),
    ]
